---
- hosts: 172.31.6.107
  become: yes
  tasks:
  - name: i want to install direct linux command
    command: hostname -f
    register: myfirsttaskresult


  - name: i want to display my first task result
    debug: 
      msg: "{{myfirsttaskresult}}" 

  - name: i want to install git
    apt:
      name: git
      state: present
    tags: mygit  
    #when: myfirsttaskresult.stderr ==""

  - name: i want to install tree
    apt:
      name: tree
      state: present
    tags: mytree  
    #when: myfirsttaskresult.stderr !=""   

