---
- hosts: 172.31.6.107
  become: yes
  gather_facts: yes
  vars:
    myvar01: git
    myvar02: wget
    myvar03: tree
  tasks:
  - name: i want to display var01
    debug:
       msg: "{{myvar01}}"