---
- hosts: all
  become: yes 
  gather_facts: yes  
  tasks:
  - name: I want to install webserver on ubuntu
    apt: 
     name: apache2
     state: present

  - name: I want to install webserver on redhat
    ansible.builtin.dnf:
      name: httpd
      state: present   