---
- hosts: all
  become: yes 
  gather_facts: yes  
  tasks:
  - name: I want to install webserver on ubuntu
    apt: 
     name: "{{mywebpackonubuntu}}"
     state: present 
    when: ansible_os_family =="Debian"

  - name: I want to start webserver on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started 
    when: ansible_os_family =="Debian"

  - name: I want to install apache2 on redhat
    ansible.builtin.dnf: 
     name: "{{mywebpackonredhat}}"
     state: present 
    when: ansible_os_family =="RedHat" 